/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: space_trash.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "space_trash.pb-c.h"
void   client_connect__init
                     (ClientConnect         *message)
{
  static const ClientConnect init_value = CLIENT_CONNECT__INIT;
  *message = init_value;
}
size_t client_connect__get_packed_size
                     (const ClientConnect *message)
{
  assert(message->base.descriptor == &client_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_connect__pack
                     (const ClientConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_connect__pack_to_buffer
                     (const ClientConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConnect *
       client_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConnect *)
     protobuf_c_message_unpack (&client_connect__descriptor,
                                allocator, len, data);
}
void   client_connect__free_unpacked
                     (ClientConnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_move__init
                     (ClientMove         *message)
{
  static const ClientMove init_value = CLIENT_MOVE__INIT;
  *message = init_value;
}
size_t client_move__get_packed_size
                     (const ClientMove *message)
{
  assert(message->base.descriptor == &client_move__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_move__pack
                     (const ClientMove *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_move__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_move__pack_to_buffer
                     (const ClientMove *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_move__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMove *
       client_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMove *)
     protobuf_c_message_unpack (&client_move__descriptor,
                                allocator, len, data);
}
void   client_move__free_unpacked
                     (ClientMove *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_move__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_quit__init
                     (ClientQuit         *message)
{
  static const ClientQuit init_value = CLIENT_QUIT__INIT;
  *message = init_value;
}
size_t client_quit__get_packed_size
                     (const ClientQuit *message)
{
  assert(message->base.descriptor == &client_quit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_quit__pack
                     (const ClientQuit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_quit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_quit__pack_to_buffer
                     (const ClientQuit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_quit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientQuit *
       client_quit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientQuit *)
     protobuf_c_message_unpack (&client_quit__descriptor,
                                allocator, len, data);
}
void   client_quit__free_unpacked
                     (ClientQuit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_quit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_message__init
                     (ClientMessage         *message)
{
  static const ClientMessage init_value = CLIENT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_message__get_packed_size
                     (const ClientMessage *message)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_message__pack
                     (const ClientMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_message__pack_to_buffer
                     (const ClientMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMessage *)
     protobuf_c_message_unpack (&client_message__descriptor,
                                allocator, len, data);
}
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_ack__init
                     (ServerAck         *message)
{
  static const ServerAck init_value = SERVER_ACK__INIT;
  *message = init_value;
}
size_t server_ack__get_packed_size
                     (const ServerAck *message)
{
  assert(message->base.descriptor == &server_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_ack__pack
                     (const ServerAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_ack__pack_to_buffer
                     (const ServerAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerAck *
       server_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerAck *)
     protobuf_c_message_unpack (&server_ack__descriptor,
                                allocator, len, data);
}
void   server_ack__free_unpacked
                     (ServerAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planet_state__init
                     (PlanetState         *message)
{
  static const PlanetState init_value = PLANET_STATE__INIT;
  *message = init_value;
}
size_t planet_state__get_packed_size
                     (const PlanetState *message)
{
  assert(message->base.descriptor == &planet_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planet_state__pack
                     (const PlanetState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planet_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planet_state__pack_to_buffer
                     (const PlanetState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planet_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlanetState *
       planet_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlanetState *)
     protobuf_c_message_unpack (&planet_state__descriptor,
                                allocator, len, data);
}
void   planet_state__free_unpacked
                     (PlanetState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planet_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trash_state__init
                     (TrashState         *message)
{
  static const TrashState init_value = TRASH_STATE__INIT;
  *message = init_value;
}
size_t trash_state__get_packed_size
                     (const TrashState *message)
{
  assert(message->base.descriptor == &trash_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trash_state__pack
                     (const TrashState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trash_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trash_state__pack_to_buffer
                     (const TrashState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trash_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrashState *
       trash_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrashState *)
     protobuf_c_message_unpack (&trash_state__descriptor,
                                allocator, len, data);
}
void   trash_state__free_unpacked
                     (TrashState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trash_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ship_state__init
                     (ShipState         *message)
{
  static const ShipState init_value = SHIP_STATE__INIT;
  *message = init_value;
}
size_t ship_state__get_packed_size
                     (const ShipState *message)
{
  assert(message->base.descriptor == &ship_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ship_state__pack
                     (const ShipState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ship_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ship_state__pack_to_buffer
                     (const ShipState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ship_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShipState *
       ship_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShipState *)
     protobuf_c_message_unpack (&ship_state__descriptor,
                                allocator, len, data);
}
void   ship_state__free_unpacked
                     (ShipState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ship_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_state__init
                     (UniverseState         *message)
{
  static const UniverseState init_value = UNIVERSE_STATE__INIT;
  *message = init_value;
}
size_t universe_state__get_packed_size
                     (const UniverseState *message)
{
  assert(message->base.descriptor == &universe_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_state__pack
                     (const UniverseState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_state__pack_to_buffer
                     (const UniverseState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseState *
       universe_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseState *)
     protobuf_c_message_unpack (&universe_state__descriptor,
                                allocator, len, data);
}
void   universe_state__free_unpacked
                     (UniverseState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planet_stats__init
                     (PlanetStats         *message)
{
  static const PlanetStats init_value = PLANET_STATS__INIT;
  *message = init_value;
}
size_t planet_stats__get_packed_size
                     (const PlanetStats *message)
{
  assert(message->base.descriptor == &planet_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planet_stats__pack
                     (const PlanetStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planet_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planet_stats__pack_to_buffer
                     (const PlanetStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planet_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlanetStats *
       planet_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlanetStats *)
     protobuf_c_message_unpack (&planet_stats__descriptor,
                                allocator, len, data);
}
void   planet_stats__free_unpacked
                     (PlanetStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planet_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ship_stats__init
                     (ShipStats         *message)
{
  static const ShipStats init_value = SHIP_STATS__INIT;
  *message = init_value;
}
size_t ship_stats__get_packed_size
                     (const ShipStats *message)
{
  assert(message->base.descriptor == &ship_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ship_stats__pack
                     (const ShipStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ship_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ship_stats__pack_to_buffer
                     (const ShipStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ship_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShipStats *
       ship_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShipStats *)
     protobuf_c_message_unpack (&ship_stats__descriptor,
                                allocator, len, data);
}
void   ship_stats__free_unpacked
                     (ShipStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ship_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   universe_stats__init
                     (UniverseStats         *message)
{
  static const UniverseStats init_value = UNIVERSE_STATS__INIT;
  *message = init_value;
}
size_t universe_stats__get_packed_size
                     (const UniverseStats *message)
{
  assert(message->base.descriptor == &universe_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t universe_stats__pack
                     (const UniverseStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &universe_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t universe_stats__pack_to_buffer
                     (const UniverseStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &universe_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UniverseStats *
       universe_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UniverseStats *)
     protobuf_c_message_unpack (&universe_stats__descriptor,
                                allocator, len, data);
}
void   universe_stats__free_unpacked
                     (UniverseStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &universe_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define client_connect__field_descriptors NULL
#define client_connect__field_indices_by_name NULL
#define client_connect__number_ranges NULL
const ProtobufCMessageDescriptor client_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientConnect",
  "ClientConnect",
  "ClientConnect",
  "",
  sizeof(ClientConnect),
  0,
  client_connect__field_descriptors,
  client_connect__field_indices_by_name,
  0,  client_connect__number_ranges,
  (ProtobufCMessageInit) client_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_move__field_descriptors[3] =
{
  {
    "ship_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientMove, ship_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dir",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMove, dir),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientMove, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_move__field_indices_by_name[] = {
  1,   /* field[1] = dir */
  0,   /* field[0] = ship_id */
  2,   /* field[2] = token */
};
static const ProtobufCIntRange client_move__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_move__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientMove",
  "ClientMove",
  "ClientMove",
  "",
  sizeof(ClientMove),
  3,
  client_move__field_descriptors,
  client_move__field_indices_by_name,
  1,  client_move__number_ranges,
  (ProtobufCMessageInit) client_move__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_quit__field_descriptors[2] =
{
  {
    "ship_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientQuit, ship_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientQuit, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_quit__field_indices_by_name[] = {
  0,   /* field[0] = ship_id */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange client_quit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client_quit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientQuit",
  "ClientQuit",
  "ClientQuit",
  "",
  sizeof(ClientQuit),
  2,
  client_quit__field_descriptors,
  client_quit__field_indices_by_name,
  1,  client_quit__number_ranges,
  (ProtobufCMessageInit) client_quit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_message__field_descriptors[3] =
{
  {
    "connect",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientMessage, kind_case),
    offsetof(ClientMessage, connect),
    &client_connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "move",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientMessage, kind_case),
    offsetof(ClientMessage, move),
    &client_move__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quit",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientMessage, kind_case),
    offsetof(ClientMessage, quit),
    &client_quit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_message__field_indices_by_name[] = {
  0,   /* field[0] = connect */
  1,   /* field[1] = move */
  2,   /* field[2] = quit */
};
static const ProtobufCIntRange client_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientMessage",
  "ClientMessage",
  "ClientMessage",
  "",
  sizeof(ClientMessage),
  3,
  client_message__field_descriptors,
  client_message__field_indices_by_name,
  1,  client_message__number_ranges,
  (ProtobufCMessageInit) client_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_ack__field_descriptors[4] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerAck, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerAck, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ship_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerAck, ship_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServerAck, has_token),
    offsetof(ServerAck, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_ack__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = ok */
  2,   /* field[2] = ship_id */
  3,   /* field[3] = token */
};
static const ProtobufCIntRange server_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor server_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerAck",
  "ServerAck",
  "ServerAck",
  "",
  sizeof(ServerAck),
  4,
  server_ack__field_descriptors,
  server_ack__field_indices_by_name,
  1,  server_ack__number_ranges,
  (ProtobufCMessageInit) server_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planet_state__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PlanetState, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name_ascii",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PlanetState, name_ascii),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PlanetState, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PlanetState, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recycle",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PlanetState, recycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash_count",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PlanetState, has_trash_count),
    offsetof(PlanetState, trash_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planet_state__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name_ascii */
  4,   /* field[4] = recycle */
  5,   /* field[5] = trash_count */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange planet_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor planet_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlanetState",
  "PlanetState",
  "PlanetState",
  "",
  sizeof(PlanetState),
  6,
  planet_state__field_descriptors,
  planet_state__field_indices_by_name,
  1,  planet_state__number_ranges,
  (ProtobufCMessageInit) planet_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trash_state__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TrashState, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TrashState, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trash_state__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange trash_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trash_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrashState",
  "TrashState",
  "TrashState",
  "",
  sizeof(TrashState),
  2,
  trash_state__field_descriptors,
  trash_state__field_indices_by_name,
  1,  trash_state__number_ranges,
  (ProtobufCMessageInit) trash_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ship_state__field_descriptors[8] =
{
  {
    "ship_ascii",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShipState, ship_ascii),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ShipState, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipState, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipState, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_amplitude",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipState, v_amplitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_angle",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ShipState, v_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShipState, cargo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capacity",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShipState, capacity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ship_state__field_indices_by_name[] = {
  1,   /* field[1] = active */
  7,   /* field[7] = capacity */
  6,   /* field[6] = cargo */
  0,   /* field[0] = ship_ascii */
  4,   /* field[4] = v_amplitude */
  5,   /* field[5] = v_angle */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange ship_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ship_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShipState",
  "ShipState",
  "ShipState",
  "",
  sizeof(ShipState),
  8,
  ship_state__field_descriptors,
  ship_state__field_indices_by_name,
  1,  ship_state__number_ranges,
  (ProtobufCMessageInit) ship_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_state__field_descriptors[8] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseState, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseState, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_trash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseState, max_trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recycling_planet",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseState, recycling_planet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_over",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UniverseState, game_over),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planets",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseState, n_planets),
    offsetof(UniverseState, planets),
    &planet_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseState, n_trash),
    offsetof(UniverseState, trash),
    &trash_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ships",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseState, n_ships),
    offsetof(UniverseState, ships),
    &ship_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_state__field_indices_by_name[] = {
  4,   /* field[4] = game_over */
  1,   /* field[1] = height */
  2,   /* field[2] = max_trash */
  5,   /* field[5] = planets */
  3,   /* field[3] = recycling_planet */
  7,   /* field[7] = ships */
  6,   /* field[6] = trash */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange universe_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor universe_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseState",
  "UniverseState",
  "UniverseState",
  "",
  sizeof(UniverseState),
  8,
  universe_state__field_descriptors,
  universe_state__field_indices_by_name,
  1,  universe_state__number_ranges,
  (ProtobufCMessageInit) universe_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planet_stats__field_descriptors[2] =
{
  {
    "name_ascii",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PlanetStats, name_ascii),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recycled",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PlanetStats, recycled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planet_stats__field_indices_by_name[] = {
  0,   /* field[0] = name_ascii */
  1,   /* field[1] = recycled */
};
static const ProtobufCIntRange planet_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planet_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlanetStats",
  "PlanetStats",
  "PlanetStats",
  "",
  sizeof(PlanetStats),
  2,
  planet_stats__field_descriptors,
  planet_stats__field_indices_by_name,
  1,  planet_stats__number_ranges,
  (ProtobufCMessageInit) planet_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ship_stats__field_descriptors[3] =
{
  {
    "ship_ascii",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShipStats, ship_ascii),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ShipStats, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShipStats, cargo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ship_stats__field_indices_by_name[] = {
  1,   /* field[1] = active */
  2,   /* field[2] = cargo */
  0,   /* field[0] = ship_ascii */
};
static const ProtobufCIntRange ship_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ship_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShipStats",
  "ShipStats",
  "ShipStats",
  "",
  sizeof(ShipStats),
  3,
  ship_stats__field_descriptors,
  ship_stats__field_indices_by_name,
  1,  ship_stats__number_ranges,
  (ProtobufCMessageInit) ship_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor universe_stats__field_descriptors[5] =
{
  {
    "roaming",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStats, roaming),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_roaming",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UniverseStats, max_roaming),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planets",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseStats, n_planets),
    offsetof(UniverseStats, planets),
    &planet_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ships",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UniverseStats, n_ships),
    offsetof(UniverseStats, ships),
    &ship_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_over",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UniverseStats, game_over),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned universe_stats__field_indices_by_name[] = {
  4,   /* field[4] = game_over */
  1,   /* field[1] = max_roaming */
  2,   /* field[2] = planets */
  0,   /* field[0] = roaming */
  3,   /* field[3] = ships */
};
static const ProtobufCIntRange universe_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor universe_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UniverseStats",
  "UniverseStats",
  "UniverseStats",
  "",
  sizeof(UniverseStats),
  5,
  universe_stats__field_descriptors,
  universe_stats__field_indices_by_name,
  1,  universe_stats__number_ranges,
  (ProtobufCMessageInit) universe_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[4] =
{
  { "DIR_UP", "DIRECTION__DIR_UP", 0 },
  { "DIR_DOWN", "DIRECTION__DIR_DOWN", 1 },
  { "DIR_LEFT", "DIRECTION__DIR_LEFT", 2 },
  { "DIR_RIGHT", "DIRECTION__DIR_RIGHT", 3 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[4] =
{
  { "DIR_DOWN", 1 },
  { "DIR_LEFT", 2 },
  { "DIR_RIGHT", 3 },
  { "DIR_UP", 0 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  4,
  direction__enum_values_by_number,
  4,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
