/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: space_trash.proto */

#ifndef PROTOBUF_C_space_5ftrash_2eproto__INCLUDED
#define PROTOBUF_C_space_5ftrash_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ClientConnect ClientConnect;
typedef struct ClientMove ClientMove;
typedef struct ClientQuit ClientQuit;
typedef struct ClientMessage ClientMessage;
typedef struct ServerAck ServerAck;
typedef struct PlanetState PlanetState;
typedef struct TrashState TrashState;
typedef struct ShipState ShipState;
typedef struct UniverseState UniverseState;
typedef struct PlanetStats PlanetStats;
typedef struct ShipStats ShipStats;
typedef struct UniverseStats UniverseStats;


/* --- enums --- */

/*
 * Direction options 
 */
typedef enum _Direction {
  DIRECTION__DIR_UP = 0,
  DIRECTION__DIR_DOWN = 1,
  DIRECTION__DIR_LEFT = 2,
  DIRECTION__DIR_RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION)
} Direction;

/* --- messages --- */

/*
 * Sent from client to server when a new player joins.
 */
struct  ClientConnect
{
  ProtobufCMessage base;
};
#define CLIENT_CONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_connect__descriptor) \
     }


/*
 * Sent from client to server when player presses a key.
 */
struct  ClientMove
{
  ProtobufCMessage base;
  char *ship_id;
  Direction dir;
  uint32_t token;
};
#define CLIENT_MOVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_move__descriptor) \
    , NULL, DIRECTION__DIR_UP, 0 }


/*
 * Sent from client to server when player is leaving.
 */
struct  ClientQuit
{
  ProtobufCMessage base;
  char *ship_id;
  uint32_t token;
};
#define CLIENT_QUIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_quit__descriptor) \
    , NULL, 0 }


typedef enum {
  CLIENT_MESSAGE__KIND__NOT_SET = 0,
  CLIENT_MESSAGE__KIND_CONNECT = 1,
  CLIENT_MESSAGE__KIND_MOVE = 2,
  CLIENT_MESSAGE__KIND_QUIT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_MESSAGE__KIND__CASE)
} ClientMessage__KindCase;

/*
 * Wrapper so we can send either connect or move as one top-level message.
 */
struct  ClientMessage
{
  ProtobufCMessage base;
  ClientMessage__KindCase kind_case;
  union {
    ClientConnect *connect;
    ClientMove *move;
    ClientQuit *quit;
  };
};
#define CLIENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_message__descriptor) \
    , CLIENT_MESSAGE__KIND__NOT_SET, {0} }


/*
 * Simple reply from server 
 */
struct  ServerAck
{
  ProtobufCMessage base;
  /*
   * true if server accepted the command
   */
  protobuf_c_boolean ok;
  /*
   * optional status text
   */
  char *msg;
  char *ship_id;
  protobuf_c_boolean has_token;
  uint32_t token;
};
#define SERVER_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_ack__descriptor) \
    , 0, NULL, NULL, 0, 0 }


struct  PlanetState
{
  ProtobufCMessage base;
  /*
   * 0..num_planets-1
   */
  uint32_t id;
  /*
   * e.g. 'A' = 65
   */
  uint32_t name_ascii;
  float x;
  float y;
  protobuf_c_boolean recycle;
  /*
   * total recycled on this planet
   */
  protobuf_c_boolean has_trash_count;
  uint32_t trash_count;
};
#define PLANET_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planet_state__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0 }


struct  TrashState
{
  ProtobufCMessage base;
  float x;
  float y;
};
#define TRASH_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trash_state__descriptor) \
    , 0, 0 }


struct  ShipState
{
  ProtobufCMessage base;
  /*
   * e.g. 'A' = 65
   */
  uint32_t ship_ascii;
  protobuf_c_boolean active;
  float x;
  float y;
  float v_amplitude;
  float v_angle;
  uint32_t cargo;
  uint32_t capacity;
};
#define SHIP_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ship_state__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0 }


struct  UniverseState
{
  ProtobufCMessage base;
  uint32_t width;
  uint32_t height;
  uint32_t max_trash;
  /*
   * index
   */
  uint32_t recycling_planet;
  protobuf_c_boolean game_over;
  size_t n_planets;
  PlanetState **planets;
  /*
   * only active trash
   */
  size_t n_trash;
  TrashState **trash;
  /*
   * all slots with active flag
   */
  size_t n_ships;
  ShipState **ships;
};
#define UNIVERSE_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_state__descriptor) \
    , 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL }


struct  PlanetStats
{
  ProtobufCMessage base;
  /*
   * e.g. 'A' = 65
   */
  uint32_t name_ascii;
  /*
   * total recycled on this planet
   */
  uint32_t recycled;
};
#define PLANET_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planet_stats__descriptor) \
    , 0, 0 }


struct  ShipStats
{
  ProtobufCMessage base;
  /*
   * e.g. 'A' = 65
   */
  uint32_t ship_ascii;
  protobuf_c_boolean active;
  /*
   * current cargo
   */
  uint32_t cargo;
};
#define SHIP_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ship_stats__descriptor) \
    , 0, 0, 0 }


struct  UniverseStats
{
  ProtobufCMessage base;
  /*
   * number of active trash
   */
  uint32_t roaming;
  /*
   * max allowed trash
   */
  uint32_t max_roaming;
  size_t n_planets;
  PlanetStats **planets;
  size_t n_ships;
  ShipStats **ships;
  protobuf_c_boolean game_over;
};
#define UNIVERSE_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&universe_stats__descriptor) \
    , 0, 0, 0,NULL, 0,NULL, 0 }


/* ClientConnect methods */
void   client_connect__init
                     (ClientConnect         *message);
size_t client_connect__get_packed_size
                     (const ClientConnect   *message);
size_t client_connect__pack
                     (const ClientConnect   *message,
                      uint8_t             *out);
size_t client_connect__pack_to_buffer
                     (const ClientConnect   *message,
                      ProtobufCBuffer     *buffer);
ClientConnect *
       client_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_connect__free_unpacked
                     (ClientConnect *message,
                      ProtobufCAllocator *allocator);
/* ClientMove methods */
void   client_move__init
                     (ClientMove         *message);
size_t client_move__get_packed_size
                     (const ClientMove   *message);
size_t client_move__pack
                     (const ClientMove   *message,
                      uint8_t             *out);
size_t client_move__pack_to_buffer
                     (const ClientMove   *message,
                      ProtobufCBuffer     *buffer);
ClientMove *
       client_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_move__free_unpacked
                     (ClientMove *message,
                      ProtobufCAllocator *allocator);
/* ClientQuit methods */
void   client_quit__init
                     (ClientQuit         *message);
size_t client_quit__get_packed_size
                     (const ClientQuit   *message);
size_t client_quit__pack
                     (const ClientQuit   *message,
                      uint8_t             *out);
size_t client_quit__pack_to_buffer
                     (const ClientQuit   *message,
                      ProtobufCBuffer     *buffer);
ClientQuit *
       client_quit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_quit__free_unpacked
                     (ClientQuit *message,
                      ProtobufCAllocator *allocator);
/* ClientMessage methods */
void   client_message__init
                     (ClientMessage         *message);
size_t client_message__get_packed_size
                     (const ClientMessage   *message);
size_t client_message__pack
                     (const ClientMessage   *message,
                      uint8_t             *out);
size_t client_message__pack_to_buffer
                     (const ClientMessage   *message,
                      ProtobufCBuffer     *buffer);
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator);
/* ServerAck methods */
void   server_ack__init
                     (ServerAck         *message);
size_t server_ack__get_packed_size
                     (const ServerAck   *message);
size_t server_ack__pack
                     (const ServerAck   *message,
                      uint8_t             *out);
size_t server_ack__pack_to_buffer
                     (const ServerAck   *message,
                      ProtobufCBuffer     *buffer);
ServerAck *
       server_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_ack__free_unpacked
                     (ServerAck *message,
                      ProtobufCAllocator *allocator);
/* PlanetState methods */
void   planet_state__init
                     (PlanetState         *message);
size_t planet_state__get_packed_size
                     (const PlanetState   *message);
size_t planet_state__pack
                     (const PlanetState   *message,
                      uint8_t             *out);
size_t planet_state__pack_to_buffer
                     (const PlanetState   *message,
                      ProtobufCBuffer     *buffer);
PlanetState *
       planet_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planet_state__free_unpacked
                     (PlanetState *message,
                      ProtobufCAllocator *allocator);
/* TrashState methods */
void   trash_state__init
                     (TrashState         *message);
size_t trash_state__get_packed_size
                     (const TrashState   *message);
size_t trash_state__pack
                     (const TrashState   *message,
                      uint8_t             *out);
size_t trash_state__pack_to_buffer
                     (const TrashState   *message,
                      ProtobufCBuffer     *buffer);
TrashState *
       trash_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trash_state__free_unpacked
                     (TrashState *message,
                      ProtobufCAllocator *allocator);
/* ShipState methods */
void   ship_state__init
                     (ShipState         *message);
size_t ship_state__get_packed_size
                     (const ShipState   *message);
size_t ship_state__pack
                     (const ShipState   *message,
                      uint8_t             *out);
size_t ship_state__pack_to_buffer
                     (const ShipState   *message,
                      ProtobufCBuffer     *buffer);
ShipState *
       ship_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ship_state__free_unpacked
                     (ShipState *message,
                      ProtobufCAllocator *allocator);
/* UniverseState methods */
void   universe_state__init
                     (UniverseState         *message);
size_t universe_state__get_packed_size
                     (const UniverseState   *message);
size_t universe_state__pack
                     (const UniverseState   *message,
                      uint8_t             *out);
size_t universe_state__pack_to_buffer
                     (const UniverseState   *message,
                      ProtobufCBuffer     *buffer);
UniverseState *
       universe_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_state__free_unpacked
                     (UniverseState *message,
                      ProtobufCAllocator *allocator);
/* PlanetStats methods */
void   planet_stats__init
                     (PlanetStats         *message);
size_t planet_stats__get_packed_size
                     (const PlanetStats   *message);
size_t planet_stats__pack
                     (const PlanetStats   *message,
                      uint8_t             *out);
size_t planet_stats__pack_to_buffer
                     (const PlanetStats   *message,
                      ProtobufCBuffer     *buffer);
PlanetStats *
       planet_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planet_stats__free_unpacked
                     (PlanetStats *message,
                      ProtobufCAllocator *allocator);
/* ShipStats methods */
void   ship_stats__init
                     (ShipStats         *message);
size_t ship_stats__get_packed_size
                     (const ShipStats   *message);
size_t ship_stats__pack
                     (const ShipStats   *message,
                      uint8_t             *out);
size_t ship_stats__pack_to_buffer
                     (const ShipStats   *message,
                      ProtobufCBuffer     *buffer);
ShipStats *
       ship_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ship_stats__free_unpacked
                     (ShipStats *message,
                      ProtobufCAllocator *allocator);
/* UniverseStats methods */
void   universe_stats__init
                     (UniverseStats         *message);
size_t universe_stats__get_packed_size
                     (const UniverseStats   *message);
size_t universe_stats__pack
                     (const UniverseStats   *message,
                      uint8_t             *out);
size_t universe_stats__pack_to_buffer
                     (const UniverseStats   *message,
                      ProtobufCBuffer     *buffer);
UniverseStats *
       universe_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   universe_stats__free_unpacked
                     (UniverseStats *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ClientConnect_Closure)
                 (const ClientConnect *message,
                  void *closure_data);
typedef void (*ClientMove_Closure)
                 (const ClientMove *message,
                  void *closure_data);
typedef void (*ClientQuit_Closure)
                 (const ClientQuit *message,
                  void *closure_data);
typedef void (*ClientMessage_Closure)
                 (const ClientMessage *message,
                  void *closure_data);
typedef void (*ServerAck_Closure)
                 (const ServerAck *message,
                  void *closure_data);
typedef void (*PlanetState_Closure)
                 (const PlanetState *message,
                  void *closure_data);
typedef void (*TrashState_Closure)
                 (const TrashState *message,
                  void *closure_data);
typedef void (*ShipState_Closure)
                 (const ShipState *message,
                  void *closure_data);
typedef void (*UniverseState_Closure)
                 (const UniverseState *message,
                  void *closure_data);
typedef void (*PlanetStats_Closure)
                 (const PlanetStats *message,
                  void *closure_data);
typedef void (*ShipStats_Closure)
                 (const ShipStats *message,
                  void *closure_data);
typedef void (*UniverseStats_Closure)
                 (const UniverseStats *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction__descriptor;
extern const ProtobufCMessageDescriptor client_connect__descriptor;
extern const ProtobufCMessageDescriptor client_move__descriptor;
extern const ProtobufCMessageDescriptor client_quit__descriptor;
extern const ProtobufCMessageDescriptor client_message__descriptor;
extern const ProtobufCMessageDescriptor server_ack__descriptor;
extern const ProtobufCMessageDescriptor planet_state__descriptor;
extern const ProtobufCMessageDescriptor trash_state__descriptor;
extern const ProtobufCMessageDescriptor ship_state__descriptor;
extern const ProtobufCMessageDescriptor universe_state__descriptor;
extern const ProtobufCMessageDescriptor planet_stats__descriptor;
extern const ProtobufCMessageDescriptor ship_stats__descriptor;
extern const ProtobufCMessageDescriptor universe_stats__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_space_5ftrash_2eproto__INCLUDED */
